//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KanOrganBagisTakipOtomasyonu.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class blood_stocks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public blood_stocks()
        {
            this.transfers = new HashSet<transfer>();
        }
    
        public int stock_id { get; set; }
        public Nullable<int> donation_id { get; set; }
        public string product_type { get; set; }
        public string blood_type { get; set; }
        public string rh_factor { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public Nullable<bool> is_used { get; set; }
        public string location_shelf { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
    
        public virtual blood_donations blood_donations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transfer> transfers { get; set; }
    }
}
