//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KanOrganBagisTakipOtomasyonu.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class blood_donations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public blood_donations()
        {
            this.blood_stocks = new HashSet<blood_stocks>();
            this.lab_tests = new HashSet<lab_tests>();
        }
    
        public int donation_id { get; set; }
        public Nullable<int> donor_id { get; set; }
        public Nullable<int> hospital_id { get; set; }
        public Nullable<System.DateTime> donation_date { get; set; }
        public string bag_barcode { get; set; }
        public Nullable<int> amount_ml { get; set; }
        public string status { get; set; }
        public string rejection_reason { get; set; }
    
        public virtual donor donor { get; set; }
        public virtual hospital hospital { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<blood_stocks> blood_stocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lab_tests> lab_tests { get; set; }
    }
}
