//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KanOrganBagisTakipOtomasyonu.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class donor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public donor()
        {
            this.blood_donations = new HashSet<blood_donations>();
            this.health_questionnaires = new HashSet<health_questionnaires>();
            this.organ_donations = new HashSet<organ_donations>();
        }
    
        public int donor_id { get; set; }
        public string tckn { get; set; }
        public string name_surname { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string gender { get; set; }
        public string blood_type { get; set; }
        public string rh_factor { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<int> city_id { get; set; }
        public Nullable<int> district_id { get; set; }
        public string address_detail { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> last_donation_date { get; set; }
        public Nullable<bool> is_organ_donor { get; set; }
        public Nullable<System.DateTime> registration_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<blood_donations> blood_donations { get; set; }
        public virtual city city { get; set; }
        public virtual district district { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<health_questionnaires> health_questionnaires { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<organ_donations> organ_donations { get; set; }
    }
}
