//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KanOrganBagisTakipOtomasyonu.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class health_questionnaires
    {
        public int questionnaire_id { get; set; }
        public Nullable<int> donor_id { get; set; }
        public Nullable<System.DateTime> form_date { get; set; }
        public Nullable<bool> is_eligible { get; set; }
    
        public virtual donor donor { get; set; }
    }
}
