//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KanOrganBagisTakipOtomasyonu.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class lab_tests
    {
        public int test_id { get; set; }
        public Nullable<int> donation_id { get; set; }
        public Nullable<System.DateTime> test_date { get; set; }
        public Nullable<bool> hepatitis_b { get; set; }
        public Nullable<bool> hepatitis_c { get; set; }
        public Nullable<bool> hiv { get; set; }
        public Nullable<bool> syphilis { get; set; }
        public string test_result { get; set; }
    
        public virtual blood_donations blood_donations { get; set; }
    }
}
