//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KanOrganBagisTakipOtomasyonu.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class organ_donations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public organ_donations()
        {
            this.transfers = new HashSet<transfer>();
        }
    
        public int organ_id { get; set; }
        public Nullable<int> donor_id { get; set; }
        public string organ_name { get; set; }
        public string tissue_type_hla { get; set; }
        public Nullable<System.DateTime> donation_date { get; set; }
        public string status { get; set; }
        public Nullable<bool> is_matched { get; set; }
    
        public virtual donor donor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transfer> transfers { get; set; }
    }
}
