//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KanOrganBagisTakipOtomasyonu.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public patient()
        {
            this.requests = new HashSet<request>();
        }
    
        public int patient_id { get; set; }
        public string tckn { get; set; }
        public string name_surname { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string blood_type { get; set; }
        public string rh_factor { get; set; }
        public Nullable<int> hospital_id { get; set; }
        public string diagnosis { get; set; }
        public string urgency_status { get; set; }
        public Nullable<System.DateTime> registration_date { get; set; }
    
        public virtual hospital hospital { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<request> requests { get; set; }
    }
}
