//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KanOrganBagisTakipOtomasyonu.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class transfer
    {
        public int transfer_id { get; set; }
        public Nullable<int> request_id { get; set; }
        public Nullable<int> stock_id { get; set; }
        public Nullable<int> organ_id { get; set; }
        public string courier_name { get; set; }
        public Nullable<System.DateTime> departure_time { get; set; }
        public Nullable<System.DateTime> actual_arrival { get; set; }
        public string status { get; set; }
    
        public virtual blood_stocks blood_stocks { get; set; }
        public virtual organ_donations organ_donations { get; set; }
        public virtual request request { get; set; }
    }
}
