//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KanOrganBagisTakipOtomasyonu.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.user_logs = new HashSet<user_logs>();
        }
    
        public int user_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> role_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string name_surname { get; set; }
        public string email { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_locked { get; set; }
        public Nullable<int> failed_login_count { get; set; }
        public Nullable<System.DateTime> last_login_date { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    
        public virtual department department { get; set; }
        public virtual role role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_logs> user_logs { get; set; }
    }
}
