//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KanOrganBagisTakipOtomasyonu.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_logs
    {
        public int log_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string action_type { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> log_date { get; set; }
        public string ip_address { get; set; }
    
        public virtual user user { get; set; }
    }
}
